/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-10-29 09:03:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Form Page</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        .container{\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            border: 1px solid black;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        #myForm table tr td input{\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        #myForm table tr {\r\n");
      out.write("             line-height: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <h1>My Form</h1>\r\n");
      out.write("\r\n");
      out.write("      <form id=\"myForm\" action=\"RegisterServlet\" method=\"post\">\r\n");
      out.write("        <table>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>Enter your name:</td>\r\n");
      out.write("            <td>\r\n");
      out.write("              <input type=\"text\" name=\"user_name\" placeholder=\"Your name\" />\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>Enter your password:</td>\r\n");
      out.write("            <td>\r\n");
      out.write("              <input\r\n");
      out.write("                type=\"password\"\r\n");
      out.write("                name=\"user_password\"\r\n");
      out.write("                placeholder=\"Enter password\"\r\n");
      out.write("              />\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>Enter your email</td>\r\n");
      out.write("            <td>\r\n");
      out.write("              <input type=\"email\" name=\"user_email\" placeholder=\"Your Email\"\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>Select Gender</td>\r\n");
      out.write("            <td>\r\n");
      out.write("              <input type=\"radio\" name=\"user_gender\" value=\"male\" />Male &nbsp;\r\n");
      out.write("              &nbsp;\r\n");
      out.write("              <input type=\"radio\" name=\"user_gender\" value=\"female\" />Female\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>Select your course</td>\r\n");
      out.write("            <td>\r\n");
      out.write("              <select name=\"user_course\">\r\n");
      out.write("                <option value=\"Java\">Java</option>\r\n");
      out.write("                <option value=\"Php\">Php</option>\r\n");
      out.write("                <option value=\"Python\">Python</option>\r\n");
      out.write("                <option value=\"JavaScript\">JavaScript</option>\r\n");
      out.write("              </select>\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td style=\"text-align: center\" colspan=\"2\">\r\n");
      out.write("              <input type=\"checkbox\" value=\"checked\" name=\"condition\" /> &nbsp;\r\n");
      out.write("              &nbsp; Agree terms and condition\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td style=\"text-align:center\" colspan=2>\r\n");
      out.write("              <button type=\"submit\">Register</button> &nbsp; &nbsp; &nbsp;\r\n");
      out.write("              <button type=\"reset\">Reset</button>\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
